### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by Follpvosten**

### CODE REVIEW

**Comment by onbjerg** [comment]
Can you make the tests pass?

**Comment by Follpvosten** [comment]
`TypeError: Failed to load plugin react: Object.assign is not a function`

Tbh, I have no idea what's going on here. This PR isn't even adding any code. May be an issue with nvm/iojs/standard? Why is it trying to load "react" anyways?

**Comment by Follpvosten** [comment]
My guess would be that because `standard` isn't being tested against iojs, there is some kind of incompatibility between those two.

**Comment by onbjerg** [comment]
@Follpvosten Yeah try that. No clue why it is loading React.

**Comment by Follpvosten** [comment]
Should be right now.

**Comment by onbjerg** [comment]
Thanks! 👍

**Pull request merged**
